package MultiThread;

public class Th3_ThreadName {
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().getName());
        MyThread th = new MyThread();
        th.start();
        System.out.println(th.getName());
        System.out.println("Before setting thread name: "+Thread.currentThread().getName());
        Thread.currentThread().setName("Arg");
        System.out.println("After setting thread name: "+Thread.currentThread().getName());
    }
}

class MyThread extends Thread {

    @Override
    public void run() {
        System.out.println("Thread name: "+Thread.currentThread().getName());
    }
}

/*
* Getting and Setting Name of a thread
* Every thread in java has some name. It may be default name generated by JVM or customized name provided by programmer.
* we can get and set name of a thread by using getName() and setName().
* */