package MultiThread;

public class Th4_ThreadPriority {
    public static void main(String[] args) {

        System.out.println(Thread.currentThread().getName()+" thread priority by default is: "+Thread.currentThread().getPriority());
//        Thread.currentThread().setPriority(15);  // Exception in thread "main" java.lang.IllegalArgumentException
        Thread.currentThread().setPriority(10);
        Th4_MyThread th = new Th4_MyThread();
        System.out.println(Thread.currentThread().getName()+" thread priority by default is: "+Thread.currentThread().getPriority());
        System.out.println(th.getName()+" thread priority now is: "+th.getPriority());
    }

}

class Th4_MyThread extends Thread {
    @Override
    public void run() {
        System.out.println("Thread name: "+Thread.currentThread().getName()+" Thread priority is: "+Thread.currentThread().getPriority());
    }
}

/*
* Every thread in java have some priority. It may be default priority generated by JVM or customized priority divided by programmer.
* Valid range of thread priority is 1-10. where 1 is min priority and 10 is max priority.
* Thread class defines the following constrents to represent some standard priority.
* Thread.MIN_PRIORITY, Thread.NORM_PRIORITY, Thread.MAX_PRIORITY
*
* Thread scheduler will use priorities while allocating processer.
* The thread which is having highest priority will get the chance first.
* If 2 thread having same priority then we can't expect exact execution order. it depends on thread scheduler.
*
* > Thread class the following method to get and set priority of a thread
*       public final int getPriority()      public final void setPriority(int p)
* Allowed value range 1-10. otherwise runtime exception IlligalArgumentException . EX- t.setPriority(17);
*
* > Default Priority default priority only for the main thread is 5.
* But for all remaining thread default priority will be inherited from parent to child.
*
* Some platform wont provides support for thread priorities.
*
* */